#########################################
##                                      #
##        Learn2Swim HTPC Docker        #
##                                      #
#################################################
##                                              #
## Configuration is read from the .env file     #
## Ensure the .env file is in this folder       #
##                                              #
#################################################

version: "3.5"

services:
  # ORGANIZR: Web Frontend for Management
  organizr:
    image: organizr/organizr
    container_name: organizr
    restart: unless-stopped
    env_file: .env
    logging:
      driver: 'json-file'
      options:
        max-file: '${LOG_FILE_NUM}'
        max-size: '${LOG_FILE_SIZE}'
    ports:
      - '${ORGANIZR_PORT}:80'
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
    volumes:
      - '/etc/localtime:/etc/localtime:ro'

  # READARR: Book Management
  readarr:
    container_name: readarr
    image: lscr.io/linuxserver/readarr:develop
    restart: unless-stopped
    env_file: .env
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
    logging:
      driver: 'json-file'
      options:
        max-file: '${LOG_FILE_NUM}'
        max-size: '${LOG_FILE_SIZE}'
    ports:
      - '${READARR_PORT}:8787'
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - '${TORRENTS_PATH}/completed:/torrents/completed'
      - '${MEDIA_BASE_PATH}/books:/books'

  # CALIBRE: Book Interface
  calibre:
    image: lscr.io/linuxserver/calibre:latest
    container_name: calibre
    security_opt:
      - seccomp:unconfined #optional
    restart: unless-stopped
    logging:
      driver: 'json-file'
      options:
        max-file: '${LOG_FILE_NUM}'
        max-size: '${LOG_FILE_SIZE}'
    ports:
      - '${CALIBRE_PORT}:8080'
      - '${CALIBRE_SERVER_PORT}:8181'
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
      - PASSWORD=${CALIBRE_AUTH}
    volumes:
      - '${TORRENTS_PATH}/completed:/torrents/completed'
      - '${MEDIA_BASE_PATH}/books:/books'
      - '/etc/localtime:/etc/localtime:ro'

  # SONARR: TV Series Management
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    restart: unless-stopped
    env_file: .env
    logging:
      driver: 'json-file'
      options:
        max-file: '${LOG_FILE_NUM}'
        max-size: '${LOG_FILE_SIZE}'
    ports:
      - '${SONARR_PORT}:8989'
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
    volumes:
      - '${TORRENTS_PATH}/completed:/torrents/completed'
      - '${MEDIA_BASE_PATH}/tv:/tv'
      - '${MEDIA_BASE_PATH}/kids/tv:/kids/tv'
      - '/etc/localtime:/etc/localtime:ro'

  # RADARR: Movie Management
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    restart: unless-stopped
    env_file: .env
    logging:
      driver: 'json-file'
      options:
        max-file: '${LOG_FILE_NUM}'
        max-size: '${LOG_FILE_SIZE}'
    ports:
      - '${RADARR_PORT}:7878'
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
    volumes:
      - '${TORRENTS_PATH}/completed:/torrents/completed'
      - '${MEDIA_BASE_PATH}/movies:/movies'
      - '${MEDIA_BASE_PATH}/kids/movies:/kids/movies'
      - '/etc/localtime:/etc/localtime:ro'

  #PLEX-SERVER: Media management & distribution service
  plex-server:
    container_name: plex-server
    image: plexinc/pms-docker:latest
    env_file: .env
    environment:
      - TZ=${TZ}
    ports:
      - '${PLEX_PORT}:7878'
    volumes:
      - '${CONFIG_PATH}/:/config'
      - '${TRANSCODE_PATH}/:/transcode'
      - '${MEDIA_BASE_PATH}/:/media'

  # DELUGEVPN: Deluge Torrent Client + VPN
  arch-delugevpn:
    image: binhex/arch-delugevpn
    container_name: delugevpn
    restart: unless-stopped
    env_file: .env
    logging:
      driver: 'json-file'
      options:
        max-file: '${LOG_FILE_NUM}'
        max-size: '${LOG_FILE_SIZE}'
    ports:
      - '${DELUGE_PORT}:8112'
      - '8118:8118'
      - '58846:58846'
      - '58946:58946'
    cap_add:
      - NET_ADMIN
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
      - VPN_ENABLED=no
      - VPN_USER=${VPNUNAME}
      - VPN_PASS=${VPNPASS}
      - VPN_REMOTE=${VPN_REMOTE}
      - VPN_PORT=1198
      - VPN_PROTOCOL=udp
      - VPN_DEVICE_TYPE=tun
      - VPN_PROV=${VPNPROVIDER}
      - STRONG_CERTS=no
      - ENABLE_PRIVOXY=yes
      - STRICT_PORT_FORWARD=yes
      - LAN_NETWORK=${CIDR_ADDRESS}
      - NAME_SERVERS=37.235.1.174,8.8.8.8,37.235.1.177,8.8.4.4
      - DEBUG=true
      - DELUGE_DAEMON_LOG_LEVEL=debug
      - DELUGE_WEB_LOG_LEVEL=debug
    volumes:
      - '${TORRENTS_PATH}/:/torrents'
      - '${CONFIG_PATH}/:/config'
      - '/etc/localtime:/etc/localtime:ro'

  # TAUTULLI: Monitoring Service for PLEX Usage
  tautulli:
    image: lscr.io/linuxserver/tautulli:latest
    container_name: tautulli
    restart: unless-stopped
    logging:
      driver: 'json-file'
      options:
        max-file: '${LOG_FILE_NUM}'
        max-size: '${LOG_FILE_SIZE}'
    ports:
      - '${TAUTULLI_PORT}:8181'
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
    volumes:
      - '/etc/localtime:/etc/localtime:ro'
