#########################################
##                                      #
##        Learn2Swim HTPC Docker        #
##                                      #
#################################################
##                                              #
## Configuration is read from the .env file     #
## Ensure the .env file is in this folder       #
##                                              #
#################################################

version: "3.5"

services:
  #PLEX: Media management & distribution service
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - VERSION=docker
      # - PLEX_CLAIM= #optional
    volumes:
      - '${CONFIG_PATH}:/config'
      - '${MEDIA_BASE_PATH}/tv:/tv'
      - '${MEDIA_BASE_PATH}/movies:/movies'
      - '${MEDIA_BASE_PATH}/books:/books'
    network_mode: host
    restart: unless-stopped

  # DELUGEVPN: Deluge Torrent Client + VPN
  deluge:
    image: binhex/arch-delugevpn
    container_name: deluge
    env_file: .env
    logging:
      driver: 'json-file'
      options:
        max-file: '${LOG_FILE_NUM}'
        max-size: '${LOG_FILE_SIZE}'
    cap_add:
      - NET_ADMIN
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
      - VPN_ENABLED=no
      - VPN_USER=${VPNUNAME}
      - VPN_PASS=${VPNPASS}
      - VPN_REMOTE=${VPN_REMOTE}
      - VPN_PORT=1198
      - VPN_PROTOCOL=udp
      - VPN_DEVICE_TYPE=tun
      - VPN_PROV=${VPNPROVIDER}
      - STRONG_CERTS=no
      - ENABLE_PRIVOXY=yes
      - STRICT_PORT_FORWARD=yes
      - LAN_NETWORK=${CIDR_ADDRESS}
      - NAME_SERVERS=37.235.1.174,8.8.8.8,37.235.1.177,8.8.4.4
      - DEBUG=true
      - DELUGE_DAEMON_LOG_LEVEL=debug
      - DELUGE_WEB_LOG_LEVEL=debug
      - DELUGE_ENABLE_WEBUI_PASSWORD=no #remove later
    volumes:
      - '${TORRENTS_PATH}:/data'
      - '${CONFIG_PATH}:/config'
      - '/etc/localtime:/etc/localtime:ro'
    ports:
      - '${DELUGE_PORT}:8112'
      - '8118:8118'
      - '58846:58846'
      - '58946:58946'
    restart: unless-stopped

  # READARR: Book Management
  readarr:
    container_name: readarr
    image: lscr.io/linuxserver/readarr:develop
    env_file: .env
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
    logging:
      driver: 'json-file'
      options:
        max-file: '${LOG_FILE_NUM}'
        max-size: '${LOG_FILE_SIZE}'
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - '${TORRENTS_PATH}/completed:/torrents/completed'
      - '${MEDIA_BASE_PATH}/books:/books'
    ports:
      - '${READARR_PORT}:8787'
    restart: unless-stopped

  # CALIBRE: Book Interface
  calibre:
    image: lscr.io/linuxserver/calibre:latest
    container_name: calibre
    security_opt:
      - seccomp:unconfined #optional
    logging:
      driver: 'json-file'
      options:
        max-file: '${LOG_FILE_NUM}'
        max-size: '${LOG_FILE_SIZE}'
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
      - PASSWORD=${CALIBRE_AUTH}
    volumes:
      - '${TORRENTS_PATH}/completed:/torrents/completed'
      - '${MEDIA_BASE_PATH}/books:/books'
      - '/etc/localtime:/etc/localtime:ro'
    ports:
      - '${CALIBRE_PORT}:8080'
      - '${CALIBRE_PORT2}:8181'
      - 8081:8081
    restart: unless-stopped

  # SONARR: TV Series Management
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    env_file: .env
    logging:
      driver: 'json-file'
      options:
        max-file: '${LOG_FILE_NUM}'
        max-size: '${LOG_FILE_SIZE}'
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
    volumes:
      - '${CONFIG_PATH}:/config'
      - '${MEDIA_BASE_PATH}/tv:/tv'
      - '${MEDIA_BASE_PATH}/new:/downloads'
      - '/etc/localtime:/etc/localtime:ro'
    ports:
      - 8989:8989
      - '${SONARR_PORT}:8989'
    restart: unless-stopped

  # RADARR: Movie Management
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    env_file: .env
    logging:
      driver: 'json-file'
      options:
        max-file: '${LOG_FILE_NUM}'
        max-size: '${LOG_FILE_SIZE}'
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
    volumes:
      - '${CONFIG_PATH}:/config'
      - '${MEDIA_BASE_PATH}/movies:/movies'
      - '${MEDIA_BASE_PATH}/new:/downloads'
      - '/etc/localtime:/etc/localtime:ro'
    ports:
      - '${RADARR_PORT}:7878'
    restart: unless-stopped

  # TAUTULLI: Monitoring Service for PLEX Usage
  tautulli:
    image: lscr.io/linuxserver/tautulli:latest
    container_name: tautulli
    logging:
      driver: 'json-file'
      options:
        max-file: '${LOG_FILE_NUM}'
        max-size: '${LOG_FILE_SIZE}'
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
    volumes:
      - '${CONFIG_PATH}:/config'
      - '/etc/localtime:/etc/localtime:ro'
    ports:
      - '${TAUTULLI_PORT}:8181'
    restart: unless-stopped

  # ORGANIZR: Web Frontend for Management
  organizr:
    image: organizr/organizr
    container_name: organizr
    env_file: .env
    logging:
      driver: 'json-file'
      options:
        max-file: '${LOG_FILE_NUM}'
        max-size: '${LOG_FILE_SIZE}'
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
    volumes:
      - '/etc/localtime:/etc/localtime:ro'
    ports:
      - '${ORGANIZR_PORT}:80'
    restart: unless-stopped
